version: '3.9'
services:

  php-fpm: # Service PHP
    build:
      context: .
      dockerfile: .dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      - ndli-net
    ports:
      - "8084:80"



  db: # Service Mariadb
    image: mariadb:latest
    networks:
      - ndli-net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NUITINFO

    volumes:
      - ./mariadb/mysql:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/ndli.sql
    restart: unless-stopped



networks:
  ndli-net:
